# Generated by Django 3.2.3 on 2021-07-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('locaton', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
