# Generated by Django 3.2.3 on 2021-07-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=30)),
                ('locaton', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Products',
        ),
    ]
