# Generated by Django 3.2.3 on 2021-07-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210704_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('estate_of_interest', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=16)),
                ('office_address', models.CharField(max_length=200)),
                ('home_address', models.CharField(max_length=200)),
            ],
        ),
    ]
