# Generated by Django 3.2.3 on 2021-06-24 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('full_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=6)),
                ('home_address', models.CharField(max_length=50)),
                ('office_address', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=30)),
                ('next_of_kin', models.CharField(max_length=30)),
                ('relationship', models.CharField(max_length=20)),
                ('estate', models.CharField(max_length=30)),
                ('plots', models.IntegerField()),
                ('amount', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('registration_date', models.DateField()),
                ('payment_complete', models.BooleanField(default=False)),
                ('documentation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('phone_number', models.IntegerField(primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_paid', models.IntegerField()),
                ('date', models.DateField()),
                ('reciept_number', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_info.customer')),
            ],
        ),
    ]
