# Generated by Django 3.2.3 on 2021-06-26 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_info', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account_detail',
            old_name='name',
            new_name='customer',
        ),
    ]
